[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["Vick Aita <75151+vickaita@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
